name: release

on:
  workflow_dispatch:
  push:
    tags: '*'

permissions:
  contents: write

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: ${{github.ref}}
        draft: false
        prerelease: false

    - name: Build pack file
      run: |
        zip -r chaosBP.mcpack . -x '.git/*' '.github/*'

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        uploadurl: ${{steps.create_release.outputs.uploadurl}}
        asset_path: ./chaosBP.mcpack
        asset_name: chaosBP.mcpack
        asset_content_type: application/zip
